# Generated by Django 4.0.3 on 2022-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlint', models.CharField(max_length=50, verbose_name='https')),
            ],
        ),
        migrations.DeleteModel(
            name='Urlc',
        ),
    ]
