# Generated by Django 4.0.3 on 2022-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_task_delete_urlc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='s', max_length=50)),
                ('article_news_block', models.CharField(default='article_news_block', max_length=50, verbose_name='Блок')),
                ('article_news_title', models.CharField(default='article_news_title', max_length=50, verbose_name='Название')),
                ('article_news_body', models.CharField(default='article_news_body', max_length=50, verbose_name='Контент')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готовность к скачиванию')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
