# Generated by Django 4.1.5 on 2023-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawledtext',
            name='parsed_text',
        ),
        migrations.AddField(
            model_name='crawledtext',
            name='original_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crawledtext',
            name='original_title',
            field=models.TextField(default=''),
        ),
    ]
