# Generated by Django 4.1.5 on 2023-01-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_crawledtext_is_translated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawledtext',
            name='is_translated',
        ),
        migrations.RemoveField(
            model_name='crawledtext',
            name='translated_text',
        ),
        migrations.RemoveField(
            model_name='crawledtext',
            name='translated_title',
        ),
    ]
